app:
  name: "go-flow"
  version: "1.0.0"
  port: 8080
  env: "development"
  http:
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
    enable_cors: true

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "go_flow"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

log:
  level: "info"
  format: "text"
  output: "both"
  lumberjack:
    filename: "logs/app.log"
    maxsize: 100
    maxage: 30
    maxbackups: 5
    compress: true 

jwt:
  secret: "zhoudm1743wBqzkwGulYSmBSMzH7mMsE"
  expires_in: "24h"
  refresh_expires: "168h"
  issuer: "go-flow"