app:
  name: go-flow-demo
  version: 0.1.0
  mode: dev

http:
  host: 0.0.0.0
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1048576

database:
  driver: sqlite
  dsn: ./go-flow.db
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s
  log_level: error

log:
  level: debug
  format: text
  output_path: stdout 

cache:
  type: memory     # 缓存类型: memory、redis 或 file
  host: localhost  # redis 主机地址，仅当 type 为 redis 时使用
  port: 6379       # redis 端口，仅当 type 为 redis 时使用
  password: ""     # redis 密码，仅当 type 为 redis 时使用
  db: 0            # redis 数据库，仅当 type 为 redis 时使用
  prefix: "goflow:" # 缓存键前缀
  file_path: "./storage/cache" # 文件缓存路径，仅当 type 为 file 时使用 