app:
  name: go-flow-demo
  version: 0.1.0
  mode: dev

http:
  host: 0.0.0.0
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1048576

database:
  driver: mysql
  dsn: root:123456@tcp(localhost:3306)/go_flow?charset=utf8mb4&parseTime=True&loc=Local
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s
  log_level: error

log:
  level: debug
  format: text
  output_path: stdout 

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  prefix: "goflow:" 