basePath: /api/v1
definitions:
  req.IdReq:
    properties:
      id:
        description: 主键ID
        type: integer
    required:
    - id
    type: object
  req.LoginReq:
    properties:
      app_id:
        type: string
      captcha:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - app_id
    - captcha
    - password
    - username
    type: object
  req.PageReq:
    properties:
      pageNo:
        description: 页码
        minimum: 1
        type: integer
      pageSize:
        description: 每页大小
        maximum: 60
        type: integer
    type: object
  req.SystemAdminAddReq:
    properties:
      avatar:
        type: string
      email:
        type: string
      nickname:
        maxLength: 30
        minLength: 3
        type: string
      password:
        maxLength: 30
        minLength: 6
        type: string
      phone:
        type: string
      role:
        items:
          type: string
        type: array
      username:
        maxLength: 30
        minLength: 3
        type: string
    required:
    - email
    - nickname
    - password
    - phone
    - role
    - username
    type: object
  req.SystemAdminEditReq:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      nickname:
        maxLength: 30
        minLength: 3
        type: string
      phone:
        type: string
      role:
        items:
          type: string
        type: array
      username:
        maxLength: 30
        minLength: 3
        type: string
    required:
    - email
    - id
    - nickname
    - phone
    - role
    - username
    type: object
  req.SystemAdminListReq:
    properties:
      nickname:
        type: string
      role:
        type: string
      status:
        type: integer
      username:
        type: string
    type: object
  resp.SystemAdminResp:
    properties:
      avatar:
        type: string
      created_at:
        type: integer
      email:
        type: string
      id:
        type: integer
      last_login_at:
        type: integer
      last_login_ip:
        type: string
      nickname:
        type: string
      phone:
        type: string
      role:
        items:
          type: string
        type: array
      status:
        type: integer
      updated_at:
        type: integer
      username:
        type: string
    type: object
  response.PageResp:
    properties:
      count:
        description: 总数
        type: integer
      lists:
        description: 数据
      pageNo:
        description: 页No
        type: integer
      pageSize:
        description: 每页Size
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 这是一个基于Go和Gin的企业级后台管理系统API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Go-Flow API
  version: "1.0"
paths:
  /api/v1/auth/captcha:
    get:
      consumes:
      - application/json
      description: 获取验证码
      produces:
      - application/json
      responses:
        "200":
          description: 获取验证码成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 获取验证码失败
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取验证码
      tags:
      - auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 登录请求
        in: body
        name: loginReq
        required: true
        schema:
          $ref: '#/definitions/req.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 登录失败
          schema:
            $ref: '#/definitions/response.Response'
      summary: 登录
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: 退出登录
      produces:
      - application/json
      responses:
        "200":
          description: 退出登录成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 退出登录失败
          schema:
            $ref: '#/definitions/response.Response'
      summary: 退出登录
      tags:
      - auth
  /api/v1/auth/refresh-token:
    get:
      consumes:
      - application/json
      description: 刷新token
      produces:
      - application/json
      responses:
        "200":
          description: 刷新token成功
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: 刷新token失败
          schema:
            $ref: '#/definitions/response.Response'
      summary: 刷新token
      tags:
      - auth
  /system/admin/add:
    post:
      consumes:
      - application/json
      description: 添加管理员
      parameters:
      - description: 添加参数
        in: body
        name: addReq
        required: true
        schema:
          $ref: '#/definitions/req.SystemAdminAddReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.Response'
      summary: 添加管理员
      tags:
      - 管理员
  /system/admin/all:
    get:
      consumes:
      - application/json
      description: 获取所有管理员
      parameters:
      - description: 查询参数
        in: body
        name: queryReq
        required: true
        schema:
          $ref: '#/definitions/req.SystemAdminListReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/resp.SystemAdminResp'
                  type: array
              type: object
      summary: 获取所有管理员
      tags:
      - 管理员
  /system/admin/change-status:
    post:
      consumes:
      - application/json
      description: 修改管理员状态
      parameters:
      - description: 管理员ID
        in: body
        name: idReq
        required: true
        schema:
          $ref: '#/definitions/req.IdReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.Response'
      summary: 修改管理员状态
      tags:
      - 管理员
  /system/admin/delete:
    post:
      consumes:
      - application/json
      description: 删除管理员
      parameters:
      - description: 管理员ID
        in: body
        name: idReq
        required: true
        schema:
          $ref: '#/definitions/req.IdReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除管理员
      tags:
      - 管理员
  /system/admin/detail:
    get:
      consumes:
      - application/json
      description: 获取管理员详情
      parameters:
      - description: 管理员ID
        in: body
        name: idReq
        required: true
        schema:
          $ref: '#/definitions/req.IdReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/resp.SystemAdminResp'
              type: object
      summary: 获取管理员详情
      tags:
      - 管理员
  /system/admin/edit:
    post:
      consumes:
      - application/json
      description: 编辑管理员
      parameters:
      - description: 编辑参数
        in: body
        name: editReq
        required: true
        schema:
          $ref: '#/definitions/req.SystemAdminEditReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.Response'
      summary: 编辑管理员
      tags:
      - 管理员
  /system/admin/list:
    get:
      consumes:
      - application/json
      description: 获取管理员列表
      parameters:
      - description: 分页参数
        in: body
        name: pageReq
        required: true
        schema:
          $ref: '#/definitions/req.PageReq'
      - description: 查询参数
        in: body
        name: queryReq
        required: true
        schema:
          $ref: '#/definitions/req.SystemAdminListReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/response.PageResp'
                  - properties:
                      lists:
                        items:
                          $ref: '#/definitions/resp.SystemAdminResp'
                        type: array
                    type: object
              type: object
      summary: 获取管理员列表
      tags:
      - 管理员
securityDefinitions:
  ApiKeyAuth:
    description: Bearer token for authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
